// P57 — Codex provider types.
//
// Aligns with the Codex app-server JSON-RPC schema:
//   account/read, account/login/start, account/logout,
//   account/rateLimits/read, thread/start, turn/start.
//
// We deliberately keep our types lean — only the fields we render or
// branch on. The full upstream schema is treated as forward-compatible
// JSON; unknown fields pass through without strict typing.

// ─── Provider mode ───────────────────────────────────────────────────

// P64 — Provider modes are now phase-aware so the UI can pick the right
// connection path based on where the app is running.
//
//   anthropicApiKey         — Anthropic Claude (default)
//   openaiApiKey            — OpenAI Chat Completions, platform key
//   openaiUserApiKey        — OpenAI Chat Completions, user-provided key
//   codexChatGPTLocal       — Phase 2: app spawns codex app-server via
//                             stdio. Only enabled when running locally /
//                             in dev / inside a desktop wrapper. Detected
//                             at runtime; never available on Vercel.
//   codexChatGPTBridge      — Phase 1: hosted app + manually configured
//                             bridge running on the user's machine. The
//                             user pastes ws://localhost:<port> + token.
//                             Marked advanced/experimental. The paste is
//                             a hosted-web limitation (Vercel can't reach
//                             the user's laptop), NOT an OpenAI rule.
//   codexChatGPTCompanion   — Phase 3: hosted app talks to a local
//                             companion that owns the codex app-server.
//                             Pairing replaces manual paste. Browser
//                             connects directly to companion via WS
//                             with PNA preflight.
//
// Selection is always user-driven; we never silently switch billing
// models or auth accounts.
export type CodexProviderMode =
  | "anthropicApiKey"
  | "openaiApiKey"
  | "openaiUserApiKey"
  | "codexChatGPTLocal"
  | "codexChatGPTBridge"
  | "codexChatGPTCompanion";

export const CODEX_PROVIDER_MODES: readonly CodexProviderMode[] = [
  "anthropicApiKey",
  "openaiApiKey",
  "openaiUserApiKey",
  "codexChatGPTLocal",
  "codexChatGPTBridge",
  "codexChatGPTCompanion",
] as const;

// True for any of the three Codex-via-ChatGPT modes. Useful for chat
// dispatch + "is this a Codex turn?" checks.
export function isCodexMode(m: CodexProviderMode): boolean {
  return m === "codexChatGPTLocal"
      || m === "codexChatGPTBridge"
      || m === "codexChatGPTCompanion";
}

// Phase-1 -> Phase-3 migration helper. Old rows might carry literal
// "codexChatGPT" (P57 enum). Translate to the new bridge mode so users
// who previously pasted bridge URLs keep working.
export function normalizeProviderMode(raw: any): CodexProviderMode {
  if (raw === "codexChatGPT") return "codexChatGPTBridge";
  if (CODEX_PROVIDER_MODES.includes(raw)) return raw as CodexProviderMode;
  return "anthropicApiKey";
}

// ─── JSON-RPC 2.0 wire types ─────────────────────────────────────────

export interface JsonRpcRequest<P = any> {
  jsonrpc: "2.0";
  id: number | string;
  method: string;
  params?: P;
}

export interface JsonRpcResponse<R = any> {
  jsonrpc: "2.0";
  id: number | string;
  result?: R;
  error?: JsonRpcError;
}

export interface JsonRpcNotification<P = any> {
  jsonrpc: "2.0";
  method: string;
  params?: P;
}

export interface JsonRpcError {
  code: number;
  message: string;
  data?: any;
}

// ─── account/* method shapes ────────────────────────────────────────
//
// P64.2 — These types are aligned with the wire protocol generated by
// `codex app-server generate-ts` against codex 0.130.0. We keep them
// minimal — only the fields we render or branch on — and treat the
// rest as forward-compatible JSON.
//
// The earlier P57 shape (`{ authMode: "none" | "chatgpt" | "apiKey",
// email?, plan?, accountId?, experimentalApi? }`) was wrong; the real
// shape wraps the account in a discriminated `Account` union and adds
// `requiresOpenaiAuth`. Existing callers that read `email` / `plan`
// directly should be updated to dig into `account` instead.

export type CodexPlanType =
  | "free"
  | "plus"
  | "pro"
  | "business"
  | "team"
  | "enterprise"
  | "edu"
  | "unknown"
  | string; // forward-compat for new plans

export type CodexAccount =
  | { type: "apiKey" }
  | { type: "chatgpt"; email: string; planType: CodexPlanType }
  | { type: "amazonBedrock" };

// account/read result.
export interface AccountReadResult {
  account: CodexAccount | null;
  requiresOpenaiAuth: boolean;
}

// account/login/start params. Real codex protocol exposes FOUR variants;
// we previously only had three. The new `chatgptAuthTokens` variant
// supports clients that already hold a valid ChatGPT JWT and want to
// hand it to codex without driving a fresh browser flow.
export type AccountLoginStartParams =
  | { type: "chatgpt"; codexStreamlinedLogin?: boolean } // PKCE browser flow
  | { type: "chatgptDeviceCode" }                        // device code flow
  | { type: "apiKey"; apiKey: string }                   // BYOK delegation
  | {
      type: "chatgptAuthTokens";
      accessToken: string;            // JWT
      chatgptAccountId: string;
      chatgptPlanType?: string | null;
    };

// account/login/start result. The real protocol always supplies a
// loginId for chatgpt + chatgptDeviceCode; the apiKey + chatgptAuthTokens
// variants don't carry one. We mirror the union shape so downstream
// code can pattern-match on `type`.
export type AccountLoginStartResult =
  | { type: "apiKey" }
  | { type: "chatgpt"; loginId: string; authUrl: string }
  | {
      type: "chatgptDeviceCode";
      loginId: string;
      verificationUrl: string;
      userCode: string;
    }
  | { type: "chatgptAuthTokens" };

// account/rateLimits/read result. Surface with caution — never assume
// these fields exist; app-server may return a partial.
export interface AccountRateLimitsResult {
  // Tokens / requests remaining in the user's current ChatGPT plan window.
  tokensRemaining?: number;
  tokensLimit?: number;
  requestsRemaining?: number;
  requestsLimit?: number;
  resetsAt?: number;     // unix ms
  windowSeconds?: number;
  // Free-form per-plan messages app-server passes through (e.g. "5h cooldown").
  message?: string;
}

// ─── thread / turn shapes ───────────────────────────────────────────
//
// P64.2 — Real codex thread/start params are extensive (model, sandbox,
// approval policy, base instructions, etc.). We stay minimal here and
// pass a best-effort `title` mapped onto thread/metadata/update if /
// when we wire that. Codex's actual ThreadStartParams accepts an empty
// object; all fields are optional.

export interface ThreadStartParams {
  model?: string;
  cwd?: string;
  // codex doesn't have a top-level `title` — use thread/name/set after
  // start to label the conversation. We accept a `title` here for
  // backward compat; the chat-bridge translates it into a follow-up
  // thread/name/set call.
  title?: string;
}
export interface ThreadStartResult {
  thread: { id: string;[k: string]: any };
  model: string;
  modelProvider: string;
  cwd: string;
  // Forward-compat: the real shape carries approvalPolicy, sandbox,
  // etc. Callers that need them should read off the JSON.
  [k: string]: any;
}

// turn/start params per real protocol — input is an array of UserInput
// items, NOT a flat string. The chat-bridge wraps user messages in
// `{ type: "text", text, text_elements: [] }` items.
export type CodexTurnUserInput =
  | { type: "text"; text: string; text_elements?: Array<any> }
  | { type: "image"; url: string }
  | { type: "localImage"; path: string }
  | { type: "skill"; name: string; path: string }
  | { type: "mention"; name: string; path: string };

export interface TurnStartParams {
  threadId: string;
  input: CodexTurnUserInput[];
  cwd?: string;
  model?: string;
  effort?: "minimal" | "low" | "medium" | "high" | string;
}
export interface TurnStartResult {
  turn: { id: string;[k: string]: any };
}

// ─── server-initiated requests ──────────────────────────────────────
//
// Codex sends these from server → client; the AppServerClient routes
// them to the registered onServerRequest handler.

export type ChatgptAuthTokensRefreshReason =
  | "expired"
  | "expiringSoon"
  | "invalidatedByServer"
  | "unspecified"
  | string;

export interface ChatgptAuthTokensRefreshParams {
  reason: ChatgptAuthTokensRefreshReason;
  previousAccountId?: string | null;
}

export interface ChatgptAuthTokensRefreshResponse {
  accessToken: string;
  chatgptAccountId: string;
  chatgptPlanType: string | null;
}

// Approvals (legacy v1 + v2 shapes co-exist in codex 0.130.0).
export interface AppServerApprovalRequestParams {
  // Free-form payload; we forward to the UI without strict typing.
  [k: string]: any;
}

// Discriminated union of all server-initiated requests we model.
// Anything else is forwarded to the handler with the raw method name
// so the UI can decide whether to surface or refuse it.
export type AppServerRequest =
  | {
      jsonrpc?: "2.0";
      id: number | string;
      method: "account/chatgptAuthTokens/refresh";
      params: ChatgptAuthTokensRefreshParams;
    }
  | {
      jsonrpc?: "2.0";
      id: number | string;
      method:
        | "applyPatchApproval"
        | "execCommandApproval"
        | "item/commandExecution/requestApproval"
        | "item/fileChange/requestApproval"
        | "item/permissions/requestApproval"
        | "item/tool/requestUserInput"
        | "item/tool/call"
        | "mcpServer/elicitation/request";
      params: AppServerApprovalRequestParams;
    }
  | {
      jsonrpc?: "2.0";
      id: number | string;
      method: string; // forward-compat for unknown methods
      params: any;
    };

// ─── streamed events from app-server ─────────────────────────────────
//
// app-server emits notifications (no id, has method) on long-running
// turns. We forward these to the chat UI. The full upstream catalogue
// is wider; we only branch on the subset we render today.

export type AppServerNotification =
  | { method: "turn/itemAdded";       params: { turnId: string; item: TurnItem } }
  | { method: "turn/itemUpdated";     params: { turnId: string; item: TurnItem } }
  | { method: "turn/finished";        params: { turnId: string; reason?: string } }
  | { method: "tool/call";            params: { turnId: string; toolName: string; arguments: any; callId: string } }
  | { method: "tool/result";          params: { turnId: string; callId: string; output: string; error?: string } }
  | { method: "command/executionRequested";
      params: { turnId: string; commandId: string; command: string; cwd?: string } }
  | { method: "file/changeRequested";
      params: { turnId: string; changeId: string; path: string; diff: string } }
  | { method: "approval/required";
      params: ApprovalRequest }
  | { method: "log";                  params: { level: "info" | "warn" | "error"; message: string } };

export interface TurnItem {
  type: "text" | "tool_use" | "tool_result" | "thinking";
  content?: string;
  // Free-form for forward-compat.
  [k: string]: any;
}

// ─── approval ───────────────────────────────────────────────────────
//
// P64.2 — Real codex emits approvals as SERVER-INITIATED REQUESTS
// (one of eight method names on ServerRequest.ts in 0.130.0). They
// carry an `id` and we MUST send a JSON-RPC response back so the turn
// can proceed. Earlier iterations modelled a "approval/respond" client
// method — that does not exist in the protocol.
//
// AppServerClient.installApprovalBridge() projects each server-
// initiated approval method onto a synthesized "approval/required"
// notification with the legacy `ApprovalRequest` shape below, so the
// existing chat-bridge UX continues to work. approvalRespond() resolves
// the right pending JSON-RPC id under the hood.

export type ApprovalKind = "command" | "file" | "network" | "tool";

export interface ApprovalRequest {
  approvalId: string;
  turnId: string;
  kind: ApprovalKind;
  // Human-readable summary the UI shows above the choice buttons.
  summary: string;
  // Optional detail the UI may render in a collapsible section.
  detail?: string;
  // For command approvals: the command string + cwd. For file: path + diff.
  command?: string;
  cwd?: string;
  path?: string;
  diff?: string;
}

export type ApprovalDecision =
  | "accept"
  | "acceptForSession"
  | "decline"
  | "cancel";

// Kept as a type alias only — the concrete dispatch path is now the
// approval bridge in AppServerClient (see installApprovalBridge).
export interface ApprovalRespondParams {
  approvalId: string;
  decision: ApprovalDecision;
}

// ─── DB row for the bridge connection ────────────────────────────────
//
// Phase 1 manual bridge has TWO sub-variants we need to track explicitly,
// because they have different reachability + safety properties:
//
//   "browser"      The user's browser tab is the client. Bridge runs
//                  on the same machine as the browser. URL is
//                  loopback / RFC1918 / *.local. Hosted Vercel server
//                  CANNOT reach this URL — only the browser can. We
//                  refuse server-side fetches when this is set.
//
//   "tunnel"       The bridge sits behind a public tunnel (ngrok,
//                  Cloudflare Tunnel, a self-hosted reverse proxy).
//                  URL is wss:// against a public DNS / IP. Hosted
//                  server can reach it AFTER passing the SSRF
//                  validator + connection-time DNS guard.
//
//   "local-server" Our Node runtime IS the user's machine (npm run
//                  dev / desktop wrapper). Server-side fetches to
//                  loopback are legitimate because it's the same host.
//                  Refused on Vercel.
//
// We default to "browser" for any new config that doesn't specify; old
// rows from P57 are inferred via inferConnectionLocationFromUrl().
export type CodexBridgeLocation = "browser" | "tunnel" | "local-server";

export interface CodexBridgeConfig {
  url: string;
  capabilityToken: string;
  experimentalApi?: boolean;
  connectionLocation?: CodexBridgeLocation;
}
